[package]
name = "rocket-testfire"
version = "0.1.0"
authors = ["Nick James <Redacted>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
